from typing import List
from pydantic import BaseModel, Field

class Source(BaseModel):
    url: str = Field(description="The URL of the source document.") 

class AgentResponse(BaseModel):
    answer: str = Field(description="The final answer generated by the agent.")
    sources: List[Source] = Field(default_factory=list, description="List of source documents used to generate the answer.")
